[2023-12-20 16:14:06] {UserService.py:404} ERROR - Error validating reset token: (psycopg2.errors.UndefinedTable) relation "bookmazon.password_reset_tokens" does not exist
LINE 2: FROM bookmazon.password_reset_tokens 
             ^

[SQL: SELECT bookmazon.password_reset_tokens.id, bookmazon.password_reset_tokens.user_email, bookmazon.password_reset_tokens.token, bookmazon.password_reset_tokens.token_status, bookmazon.password_reset_tokens.update_datetime, bookmazon.password_reset_tokens.create_datetime 
FROM bookmazon.password_reset_tokens 
WHERE bookmazon.password_reset_tokens.token = %(token_1)s]
[parameters: {'token_1': 'NMYbtuFNj2HMzl4nprqVtl-NT5oQg75QwWDuUu-Phmw'}]
(Background on this error at: https://sqlalche.me/e/20/f405)
[2023-12-20 16:14:06] {UserService.py:404} ERROR - Error validating reset token: (psycopg2.errors.UndefinedTable) relation "bookmazon.password_reset_tokens" does not exist
LINE 2: FROM bookmazon.password_reset_tokens 
             ^

[SQL: SELECT bookmazon.password_reset_tokens.id, bookmazon.password_reset_tokens.user_email, bookmazon.password_reset_tokens.token, bookmazon.password_reset_tokens.token_status, bookmazon.password_reset_tokens.update_datetime, bookmazon.password_reset_tokens.create_datetime 
FROM bookmazon.password_reset_tokens 
WHERE bookmazon.password_reset_tokens.token = %(token_1)s]
[parameters: {'token_1': 'NMYbtuFNj2HMzl4nprqVtl-NT5oQg75QwWDuUu-Phmw'}]
(Background on this error at: https://sqlalche.me/e/20/f405)
[2023-12-20 16:14:06] {UserService.py:404} ERROR - Error validating reset token: (psycopg2.errors.UndefinedTable) relation "bookmazon.password_reset_tokens" does not exist
LINE 2: FROM bookmazon.password_reset_tokens 
             ^

[SQL: SELECT bookmazon.password_reset_tokens.id, bookmazon.password_reset_tokens.user_email, bookmazon.password_reset_tokens.token, bookmazon.password_reset_tokens.token_status, bookmazon.password_reset_tokens.update_datetime, bookmazon.password_reset_tokens.create_datetime 
FROM bookmazon.password_reset_tokens 
WHERE bookmazon.password_reset_tokens.token = %(token_1)s]
[parameters: {'token_1': 'NMYbtuFNj2HMzl4nprqVtl-NT5oQg75QwWDuUu-Phmw'}]
(Background on this error at: https://sqlalche.me/e/20/f405)
[2023-12-20 16:14:06] {UserService.py:404} ERROR - Error validating reset token: (psycopg2.errors.UndefinedTable) relation "bookmazon.password_reset_tokens" does not exist
LINE 2: FROM bookmazon.password_reset_tokens 
             ^

[SQL: SELECT bookmazon.password_reset_tokens.id, bookmazon.password_reset_tokens.user_email, bookmazon.password_reset_tokens.token, bookmazon.password_reset_tokens.token_status, bookmazon.password_reset_tokens.update_datetime, bookmazon.password_reset_tokens.create_datetime 
FROM bookmazon.password_reset_tokens 
WHERE bookmazon.password_reset_tokens.token = %(token_1)s]
[parameters: {'token_1': 'NMYbtuFNj2HMzl4nprqVtl-NT5oQg75QwWDuUu-Phmw'}]
(Background on this error at: https://sqlalche.me/e/20/f405)
