[2023-12-20 16:14:05] {CartService.py:193} ERROR - Database transaction error: This Session's transaction has been rolled back due to a previous exception during flush. To begin a new transaction with this Session, first issue Session.rollback(). Original exception was: (raised as a result of Query-invoked autoflush; consider using a session.no_autoflush block if this flush is occurring prematurely)
(psycopg2.errors.StringDataRightTruncation) value too long for type character varying(20)

[SQL: INSERT INTO bookmazon.cart (user_account, update_datetime, create_datetime) VALUES (%(user_account)s, %(update_datetime)s, %(create_datetime)s) RETURNING bookmazon.cart.cart_id]
[parameters: {'user_account': 'invalid_user_account1', 'update_datetime': datetime.datetime(2023, 12, 20, 16, 14, 4, 531570), 'create_datetime': datetime.datetime(2023, 12, 20, 16, 14, 5, 146020)}]
(Background on this error at: https://sqlalche.me/e/20/9h9h) (Background on this error at: https://sqlalche.me/e/20/7s2a)
[2023-12-20 16:14:05] {CartService.py:193} ERROR - Database transaction error: This Session's transaction has been rolled back due to a previous exception during flush. To begin a new transaction with this Session, first issue Session.rollback(). Original exception was: (raised as a result of Query-invoked autoflush; consider using a session.no_autoflush block if this flush is occurring prematurely)
(psycopg2.errors.StringDataRightTruncation) value too long for type character varying(20)

[SQL: INSERT INTO bookmazon.cart (user_account, update_datetime, create_datetime) VALUES (%(user_account)s, %(update_datetime)s, %(create_datetime)s) RETURNING bookmazon.cart.cart_id]
[parameters: {'user_account': 'invalid_user_account1', 'update_datetime': datetime.datetime(2023, 12, 20, 16, 14, 4, 531570), 'create_datetime': datetime.datetime(2023, 12, 20, 16, 14, 5, 146020)}]
(Background on this error at: https://sqlalche.me/e/20/9h9h) (Background on this error at: https://sqlalche.me/e/20/7s2a)
[2023-12-20 16:14:05] {CartService.py:193} ERROR - Database transaction error: This Session's transaction has been rolled back due to a previous exception during flush. To begin a new transaction with this Session, first issue Session.rollback(). Original exception was: (raised as a result of Query-invoked autoflush; consider using a session.no_autoflush block if this flush is occurring prematurely)
(psycopg2.errors.StringDataRightTruncation) value too long for type character varying(20)

[SQL: INSERT INTO bookmazon.cart (user_account, update_datetime, create_datetime) VALUES (%(user_account)s, %(update_datetime)s, %(create_datetime)s) RETURNING bookmazon.cart.cart_id]
[parameters: {'user_account': 'invalid_user_account1', 'update_datetime': datetime.datetime(2023, 12, 20, 16, 14, 4, 531570), 'create_datetime': datetime.datetime(2023, 12, 20, 16, 14, 5, 146020)}]
(Background on this error at: https://sqlalche.me/e/20/9h9h) (Background on this error at: https://sqlalche.me/e/20/7s2a)
[2023-12-20 16:14:05] {CartService.py:193} ERROR - Database transaction error: This Session's transaction has been rolled back due to a previous exception during flush. To begin a new transaction with this Session, first issue Session.rollback(). Original exception was: (raised as a result of Query-invoked autoflush; consider using a session.no_autoflush block if this flush is occurring prematurely)
(psycopg2.errors.StringDataRightTruncation) value too long for type character varying(20)

[SQL: INSERT INTO bookmazon.cart (user_account, update_datetime, create_datetime) VALUES (%(user_account)s, %(update_datetime)s, %(create_datetime)s) RETURNING bookmazon.cart.cart_id]
[parameters: {'user_account': 'invalid_user_account1', 'update_datetime': datetime.datetime(2023, 12, 20, 16, 14, 4, 531570), 'create_datetime': datetime.datetime(2023, 12, 20, 16, 14, 5, 146020)}]
(Background on this error at: https://sqlalche.me/e/20/9h9h) (Background on this error at: https://sqlalche.me/e/20/7s2a)
