[32mINFO    [0m sqlalchemy.engine.Engine:base.py:1848 INSERT INTO bookmazon.cart (user_account, update_datetime, create_datetime) VALUES (%(user_account)s, %(update_datetime)s, %(create_datetime)s) RETURNING bookmazon.cart.cart_id
[32mINFO    [0m sqlalchemy.engine.Engine:base.py:1848 [generated in 0.00036s] {'user_account': 'invalid_user_account1', 'update_datetime': datetime.datetime(2023, 12, 20, 16, 14, 4, 531570), 'create_datetime': datetime.datetime(2023, 12, 20, 16, 14, 5, 146020)}
[32mINFO    [0m sqlalchemy.engine.Engine:base.py:2692 ROLLBACK
[31m[1mERROR   [0m C:\Users\user\PycharmProjects\pythonProject\bookmazon\utils\logger.py:CartService.py:171 Database error during cart retrieval: (raised as a result of Query-invoked autoflush; consider using a session.no_autoflush block if this flush is occurring prematurely)
(psycopg2.errors.StringDataRightTruncation) value too long for type character varying(20)

[SQL: INSERT INTO bookmazon.cart (user_account, update_datetime, create_datetime) VALUES (%(user_account)s, %(update_datetime)s, %(create_datetime)s) RETURNING bookmazon.cart.cart_id]
[parameters: {'user_account': 'invalid_user_account1', 'update_datetime': datetime.datetime(2023, 12, 20, 16, 14, 4, 531570), 'create_datetime': datetime.datetime(2023, 12, 20, 16, 14, 5, 146020)}]
(Background on this error at: https://sqlalche.me/e/20/9h9h)