[32mINFO    [0m sqlalchemy.engine.Engine:base.py:1848 SELECT bookmazon."user".user_account, bookmazon."user".user_password, bookmazon."user".user_name, bookmazon."user".user_gender, bookmazon."user".user_identification, bookmazon."user".user_email, bookmazon."user".user_birthday, bookmazon."user".update_datetime, bookmazon."user".create_datetime 
FROM bookmazon."user" 
WHERE bookmazon."user".user_account = %(user_account_1)s
[32mINFO    [0m sqlalchemy.engine.Engine:base.py:1848 [cached since 0.05391s ago] {'user_account_1': 'test_user1'}
[31m[1mERROR   [0m C:\Users\user\PycharmProjects\pythonProject\bookmazon\utils\logger.py:UserService.py:42 Authentication failed: No row was found when one was required